export interface VerticalConfig {
  key: string
  label: string
  shortLabel: string
  description: string
  icon: string
  accentClass: string
  accentColor: string
  table: string
  accessTable: string
  accessIdField: string
  rpc: string
  rpcParam: string
  nameField: string
  idField: string
}

export const VERTICALS: Record<string, VerticalConfig> = {
  dealflow: {
    key: 'dealflow',
    label: 'Investment Deal Flow',
    shortLabel: 'Deal Flow',
    description: 'Track VC/PE-backed companies & funding rounds',
    icon: '💼',
    accentClass: 'accent-dealflow',
    accentColor: '#2563eb',
    table: 'companies',
    accessTable: 'company_access',
    accessIdField: 'company_id',
    rpc: 'unlock_companies_secure',
    rpcParam: 'p_company_ids',
    nameField: 'company_name',
    idField: 'id',
  },
  salesintel: {
    key: 'salesintel',
    label: 'Sales Intelligence',
    shortLabel: 'Sales Intel',
    description: 'B2B lead database with verified contact signals',
    icon: '🎯',
    accentClass: 'accent-salesintel',
    accentColor: '#16a34a',
    table: 'b2b_leads',
    accessTable: 'lead_access',
    accessIdField: 'lead_id',
    rpc: 'unlock_leads_secure',
    rpcParam: 'p_lead_ids',
    nameField: 'company',
    idField: 'id',
  },
  supplyintel: {
    key: 'supplyintel',
    label: 'Supply Chain Intelligence',
    shortLabel: 'Supply Chain',
    description: 'Supplier risk, logistics & compliance data',
    icon: '🔗',
    accentClass: 'accent-supplyintel',
    accentColor: '#dc2626',
    table: 'suppliers',
    accessTable: 'supplier_access',
    accessIdField: 'supplier_id',
    rpc: 'unlock_suppliers_secure',
    rpcParam: 'p_supplier_ids',
    nameField: 'supplier_name',
    idField: 'id',
  },
  clinicalintel: {
    key: 'clinicalintel',
    label: 'Clinical Trial Matcher',
    shortLabel: 'Clinical Trials',
    description: 'Active clinical trials with eligibility & sponsor data',
    icon: '🧬',
    accentClass: 'accent-clinicalintel',
    accentColor: '#0891b2',
    table: 'clinical_trials',
    accessTable: 'trial_access',
    accessIdField: 'trial_id',
    rpc: 'unlock_trials_secure',
    rpcParam: 'p_trial_ids',
    nameField: 'trial_title',
    idField: 'id',
  },
  legalintel: {
    key: 'legalintel',
    label: 'Legal Case Intelligence',
    shortLabel: 'Legal Intel',
    description: 'Litigation tracking, counsel & damages data',
    icon: '⚖️',
    accentClass: 'accent-legalintel',
    accentColor: '#7c3aed',
    table: 'legal_cases',
    accessTable: 'case_access',
    accessIdField: 'case_id',
    rpc: 'unlock_cases_secure',
    rpcParam: 'p_case_ids',
    nameField: 'case_title',
    idField: 'id',
  },
  marketresearch: {
    key: 'marketresearch',
    label: 'Market Research Hub',
    shortLabel: 'Market Research',
    description: 'Brand sentiment, trends & category intelligence',
    icon: '📊',
    accentClass: 'accent-marketresearch',
    accentColor: '#ea580c',
    table: 'market_entities',
    accessTable: 'entity_access',
    accessIdField: 'entity_id',
    rpc: 'unlock_entities_secure',
    rpcParam: 'p_entity_ids',
    nameField: 'brand_name',
    idField: 'id',
  },
  academicintel: {
    key: 'academicintel',
    label: 'Academic Research Platform',
    shortLabel: 'Academic Intel',
    description: 'Research papers, citations & funding intelligence',
    icon: '🎓',
    accentClass: 'accent-academicintel',
    accentColor: '#0284c7',
    table: 'papers',
    accessTable: 'paper_access',
    accessIdField: 'paper_id',
    rpc: 'unlock_papers_secure',
    rpcParam: 'p_paper_ids',
    nameField: 'title',
    idField: 'id',
  },
  creatorintel: {
    key: 'creatorintel',
    label: 'Creator Marketplace',
    shortLabel: 'Creator Intel',
    description: 'Influencer & creator audience analytics',
    icon: '✨',
    accentClass: 'accent-creatorintel',
    accentColor: '#db2777',
    table: 'creators',
    accessTable: 'creator_access',
    accessIdField: 'creator_id',
    rpc: 'unlock_creators_secure',
    rpcParam: 'p_creator_ids',
    nameField: 'creator_name',
    idField: 'id',
  },
  gamingintel: {
    key: 'gamingintel',
    label: 'Gaming Studio Tracker',
    shortLabel: 'Gaming Intel',
    description: 'Game studio funding, engine & Metacritic data',
    icon: '🎮',
    accentClass: 'accent-gamingintel',
    accentColor: '#9333ea',
    table: 'game_studios',
    accessTable: 'studio_access',
    accessIdField: 'studio_id',
    rpc: 'unlock_studios_secure',
    rpcParam: 'p_studio_ids',
    nameField: 'studio_name',
    idField: 'id',
  },
  realestateintel: {
    key: 'realestateintel',
    label: 'Real Estate Intelligence',
    shortLabel: 'Real Estate',
    description: 'Property valuations, debt maturity & risk flags',
    icon: '🏢',
    accentClass: 'accent-realestateintel',
    accentColor: '#0d9488',
    table: 'properties',
    accessTable: 'property_access',
    accessIdField: 'property_id',
    rpc: 'unlock_properties_secure',
    rpcParam: 'p_property_ids',
    nameField: 'property_name',
    idField: 'id',
  },
  privatecreditintel: {
    key: 'privatecreditintel',
    label: 'Private Company Financial Intelligence',
    shortLabel: 'Private Credit',
    description: 'Credit risk, UCC liens & financial signals',
    icon: '🏦',
    accentClass: 'accent-privatecreditintel',
    accentColor: '#b45309',
    table: 'private_companies',
    accessTable: 'pc_company_access',
    accessIdField: 'company_id',
    rpc: 'unlock_private_companies_secure',
    rpcParam: 'p_company_ids',
    nameField: 'company_name',
    idField: 'id',
  },
  cyberintel: {
    key: 'cyberintel',
    label: 'Cybersecurity Intelligence',
    shortLabel: 'Cyber Intel',
    description: 'Security posture, CVEs & breach history',
    icon: '🛡️',
    accentClass: 'accent-cyberintel',
    accentColor: '#059669',
    table: 'organizations',
    accessTable: 'org_access',
    accessIdField: 'org_id',
    rpc: 'unlock_organizations_secure',
    rpcParam: 'p_org_ids',
    nameField: 'organization_name',
    idField: 'id',
  },
  biopharmintel: {
    key: 'biopharmintel',
    label: 'Pharma Pipeline Intelligence',
    shortLabel: 'BioPharma',
    description: 'Drug programs, phase & development status',
    icon: '💊',
    accentClass: 'accent-biopharmintel',
    accentColor: '#4f46e5',
    table: 'drug_programs',
    accessTable: 'program_access',
    accessIdField: 'program_id',
    rpc: 'unlock_programs_secure',
    rpcParam: 'p_program_ids',
    nameField: 'program_name',
    idField: 'id',
  },
  industrialintel: {
    key: 'industrialintel',
    label: 'Manufacturing & Industrial Intelligence',
    shortLabel: 'Industrial Intel',
    description: 'Facility capacity, risk & compliance tracking',
    icon: '🏭',
    accentClass: 'accent-industrialintel',
    accentColor: '#d97706',
    table: 'industrial_facilities',
    accessTable: 'facility_access',
    accessIdField: 'facility_id',
    rpc: 'unlock_facilities_secure',
    rpcParam: 'p_facility_ids',
    nameField: 'facility_name',
    idField: 'id',
  },
  govintel: {
    key: 'govintel',
    label: 'Government Contract Intelligence',
    shortLabel: 'Gov Intel',
    description: 'Federal & state procurement opportunities',
    icon: '🏛️',
    accentClass: 'accent-govintel',
    accentColor: '#1d4ed8',
    table: 'gov_opportunities',
    accessTable: 'opportunity_access',
    accessIdField: 'opportunity_id',
    rpc: 'unlock_opportunities_secure',
    rpcParam: 'p_opportunity_ids',
    nameField: 'opportunity_title',
    idField: 'id',
  },
  insuranceintel: {
    key: 'insuranceintel',
    label: 'Insurance Intelligence',
    shortLabel: 'Insurance Intel',
    description: 'Carrier, broker & compliance intelligence',
    icon: '🔒',
    accentClass: 'accent-insuranceintel',
    accentColor: '#0f766e',
    table: 'insurance_accounts',
    accessTable: 'account_access',
    accessIdField: 'account_id',
    rpc: 'unlock_accounts_secure',
    rpcParam: 'p_account_ids',
    nameField: 'account_name',
    idField: 'id',
  },
}

export const VERTICAL_KEYS = Object.keys(VERTICALS)
export const VERTICAL_LIST = Object.values(VERTICALS)
